### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by gpapin** [ridiculousfish/one-second-dash#1]
```
pi@raspberrypi:~/one-second-dash $ ./start.sh
+ [[ 2 -ne 2 ]]
+ CHANNEL=2
+ CAP_FIELD='Capabilities: 0x172'
+ PHYIDX=
++ seq 10
+ for IDX in '$(seq 10)'
+ iw phy phy1 info
+ grep -q 'Capabilities: 0x172'
+ PHYIDX=1
+ break
+ test -z 1
+ iw dev
+ grep -q wlan1
+ MONITOR_NAME=DoorbellMonitor
+ sudo iw dev DoorbellMonitor del
+ sudo iw phy phy1 interface add DoorbellMonitor type monitor
+ sudo ifconfig DoorbellMonitor up
+ sudo iw dev DoorbellMonitor set channel 2
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on DoorbellMonitor, link-type IEEE802_11_RADIO (802.11 plus radiotap header), capture size 256 bytes
18:37:48.534111 1.0 Mb/s 2417 MHz 11b -69dB signal antenna 1 Beacon (dash-door) [1.0* 2.0* 5.5* 11.0* 9.0 18.0 36.0 54.0 Mbit] ESS CH: 2, PRIVACY
Traceback (most recent call last):
  File "./doorbell.py", line 41, in <module>
    do_ring()
  File "./doorbell.py", line 24, in do_ring
    stdin=DEVNULL, stdout=DEVNULL, stderr=DEVNULL)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
./start.sh: line 24: break: only meaningful in a `for', `while', or `until' loop
pi@raspberrypi:~/one-second-dash $ 19 packets captured
19 packets received by filter
0 packets dropped by kernel

pi@raspberrypi:~/one-second-dash $
```

Not sure what's going on here, here is the output of a ls -al in case it helps:

```
pi@raspberrypi:~/one-second-dash $ ls -al
total 640
drwxr-xr-x 3 pi pi   4096 Oct  1 18:36 .
drwxr-xr-x 3 pi pi   4096 Oct  1 18:36 ..
-rwxr-xr-x 1 pi pi   1255 Sep 22 19:48 doorbell.py
-rw-r--r-- 1 pi pi 615120 Sep 22 19:48 doorbell.wav
drwxr-xr-x 8 pi pi   4096 Sep 22 19:48 .git
-rw-r--r-- 1 pi pi    844 Sep 22 19:48 LICENSE
-rw-r--r-- 1 pi pi   4370 Sep 22 19:48 README.md
-rwxr-xr-x 1 pi pi    843 Sep 22 19:48 setup_monitor_interface.sh
-rwxr-xr-x 1 pi pi    743 Oct  1 18:30 start.sh
```

**Comment by ridiculousfish** [comment]
Looks like perhaps `alsaplayer` isn't installed. Does `sudo apt-get alsaplayer` resolve this?

**Comment by gpapin** [comment]
it wasn't installed indeed.
I'm running this script on raspbian and here are the command I had to run to fix it:
`sudo apt-get install alsaplayer`
`sudo apt-get install alsaplayer-text`

Now it's running just fine, I guess it's not necessary if you want to do something else than playing a song. Thanks for this script !

**Comment by ridiculousfish** [comment]
Awesome, I'll add that to the readme.

**Comment by gpapin** [comment]
Cool that will definitely help others although you forgot the `install` in
`sudo apt-get alsaplayer alsaplayer-text # if you want it to play a sound`
For the lazy copy paster like me :p

**Comment by ridiculousfish** [comment]
D'oh! Fixed, thanks.
